### ISSUE TITLE
perf: avoid calculating branch node children if possible

### ISSUE THREAD

**Issue by DaniPopes** [alloy-rs/trie#48]
In `HashBuilder::push_branch_node` we calculate and return `let children = branch_node.child_hashes(hash_mask).collect();`, however this value is only observed if `updated_branch_nodes` is present.

**Comment by DaniPopes** [comment]
Is `updated_branch_nodes` used anywhere? I don't see it being used in reth @rkrasiuk

**Comment by mattsse** [comment]
it is not used in reth

only initialized as None

https://github.com/paradigmxyz/reth/blob/1bbf8b63063eedcb7a0bc07d1d026c0e8344635c/crates/trie/common/src/hash_builder/state.rs#L45-L45

**Comment by DaniPopes** [comment]
nvm found it, grep for `.with_updates`, i was looking for `set_updates`
